   name: Deploy Laravel App

   on:
     push:
       branches:
         - main  # Trigger on pushes to the main branch

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up PHP
         uses: shivammathur/setup-php@v2
         with:
           php-version: '8.1'  # Adjust based on your PHP version

       - name: Install dependencies
         run: composer install --no-dev --prefer-dist --no-progress --no-suggest

       - name: Copy files to server
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           source: "./"
           target: "/var/www/html"

       - name: Execute remote commands
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.SERVER_IP }}
           username: ${{ secrets.SSH_USER }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             cd /var/www/html
             sudo chgrp -R www-data storage bootstrap/cache
             sudo chmod -R ug+rwx storage bootstrap/cache
             php artisan migrate --force
             php artisan config:cache
